In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

**PART FOR CHANGES FOR ISW AND TELEGRAM**

In [ ]:
path = '/content/drive/MyDrive/Data/processed_data/'

df_isw_tfidf = pd.read_csv(path + 'isw_data_tfidf.csv')
df_isw_tfidf.shape

(1261, 502)

In [ ]:
df_isw_tfidf.columns.tolist()[-5:]

['497', '498', '499', 'date', 'date_plus_1']

In [ ]:
df_isw_tfidf['date'].head(5)

0    2022-02-24
1    2022-02-25
2    2022-02-26
3    2022-02-27
4    2022-02-28
Name: date, dtype: object

In [ ]:
df_isw_tfidf['date'] = pd.to_datetime(df_isw_tfidf['date'])
df_isw_tfidf['date'].dtype

dtype('<M8[ns]')

In [ ]:
df_isw_tfidf['date'].min()

Timestamp('2022-02-24 00:00:00')

In [ ]:
df_isw_tfidf['date'].max()

Timestamp('2026-03-16 00:00:00')

In [ ]:
tfidf_cols = [str(i) for i in range(100)]
df_isw_tfidf = df_isw_tfidf.rename(
    columns={col: f'isw_tfidf_{col}' for col in tfidf_cols}
)
df_isw_tfidf.columns.tolist()[-5:]

['isw_tfidf_497', 'isw_tfidf_498', 'isw_tfidf_499', 'date', 'date_plus_1']

In [ ]:
# For expanding ISW article to 24 hours
def expand_isw_hours(row):
    hours = pd.date_range(
        start=row['date'],
        periods=24,
        freq='h'
    )
    df_temp = pd.DataFrame({'datetime': hours})
    for col in [c for c in df_isw_tfidf.columns if c.startswith('isw_tfidf_')]:
        df_temp[col] = row[col]
    return df_temp

df_isw_hourly = pd.concat(
    df_isw_tfidf.apply(expand_isw_hours, axis=1).tolist(),
    ignore_index=True
)

df_isw_hourly.shape

Streaming output truncated to the last 5000 lines.
/tmp/ipykernel_36332/1634857678.py:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_temp[col] = row[col]
/tmp/ipykernel_36332/1634857678.py:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_temp[col] = row[col]
/tmp/ipykernel_36332/1634857678.py:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_temp[col] = row[col]
/tmp/ipykernel_36332/1634857678.py:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_temp[col] = row[col]
/tmp/ipykernel_36332/1634857678.py:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_temp[col] = row[col]
/tmp/ipykernel_36332/1634857678.py:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_temp[col] = row[col]
/tmp/ipykernel_36332/1634857678.py:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_temp[col] = row[col]
/tmp/ipykernel_36332/1634857678.py:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_temp[col] = row[col]
/tmp/ipykernel_36332/1634857678.py:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_temp[col] = row[col]
/tmp/ipykernel_36332/1634857678.py:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_temp[col] = row[col]
/tmp/ipykernel_36332/1634857678.py:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_temp[col] = row[col]
/tmp/ipykernel_36332/1634857678.py:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_temp[col] = row[col]
/tmp/ipykernel_36332/1634857678.py:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_temp[col] = row[col]
/tmp/ipykernel_36332/1634857678.py:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_temp[col] = row[col]
/tmp/ipykernel_36332/1634857678.py:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_temp[col] = row[col]
/tmp/ipykernel_36332/1634857678.py:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_temp[col] = row[col]
/tmp/ipykernel_36332/1634857678.py:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_temp[col] = row[col]
/tmp/ipykernel_36332/1634857678.py:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_temp[col] = row[col]
/tmp/ipykernel_36332/1634857678.py:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_temp[col] = row[col]
/tmp/ipykernel_36332/1634857678.py:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_temp[col] = row[col]
/tmp/ipykernel_36332/1634857678.py:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_temp[col] = row[col]
/tmp/ipykernel_36332/1634857678.py:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_temp[col] = row[col]
/tmp/ipykernel_36332/1634857678.py:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_temp[col] = row[col]
/tmp/ipykernel_36332/1634857678.py:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_temp[col] = row[col]
/tmp/ipykernel_36332/1634857678.py:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_temp[col] = row[col]
/tmp/ipykernel_36332/1634857678.py:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_temp[col] = row[col]
/tmp/ipykernel_36332/1634857678.py:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_temp[col] = row[col]
/tmp/ipykernel_36332/1634857678.py:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_temp[col] = row[col]
/tmp/ipykernel_36332/1634857678.py:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_temp[col] = row[col]
/tmp/ipykernel_36332/1634857678.py:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_temp[col] = row[col]
/tmp/ipykernel_36332/1634857678.py:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_temp[col] = row[col]
/tmp/ipykernel_36332/1634857678.py:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_temp[col] = row[col]
/tmp/ipykernel_36332/1634857678.py:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_temp[col] = row[col]
/tmp/ipykernel_36332/1634857678.py:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_temp[col] = row[col]
/tmp/ipykernel_36332/1634857678.py:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_temp[col] = row[col]
/tmp/ipykernel_36332/1634857678.py:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_temp[col] = row[col]
/tmp/ipykernel_36332/1634857678.py:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_temp[col] = row[col]
/tmp/ipykernel_36332/1634857678.py:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_temp[col] = row[col]
/tmp/ipykernel_36332/1634857678.py:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_temp[col] = row[col]
/tmp/ipykernel_36332/1634857678.py:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_temp[col] = row[col]
/tmp/ipykernel_36332/1634857678.py:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_temp[col] = row[col]
/tmp/ipykernel_36332/1634857678.py:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_temp[col] = row[col]
/tmp/ipykernel_36332/1634857678.py:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_temp[col] = row[col]
/tmp/ipykernel_36332/1634857678.py:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_temp[col] = row[col]
/tmp/ipykernel_36332/1634857678.py:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_temp[col] = row[col]
/tmp/ipykernel_36332/1634857678.py:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_temp[col] = row[col]
/tmp/ipykernel_36332/1634857678.py:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_temp[col] = row[col]
/tmp/ipykernel_36332/1634857678.py:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_temp[col] = row[col]
/tmp/ipykernel_36332/1634857678.py:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_temp[col] = row[col]
/tmp/ipykernel_36332/1634857678.py:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_temp[col] = row[col]
/tmp/ipykernel_36332/1634857678.py:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_temp[col] = row[col]
/tmp/ipykernel_36332/1634857678.py:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_temp[col] = row[col]
/tmp/ipykernel_36332/1634857678.py:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_temp[col] = row[col]
/tmp/ipykernel_36332/1634857678.py:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_temp[col] = row[col]
/tmp/ipykernel_36332/1634857678.py:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_temp[col] = row[col]
/tmp/ipykernel_36332/1634857678.py:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_temp[col] = row[col]
/tmp/ipykernel_36332/1634857678.py:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_temp[col] = row[col]
/tmp/ipykernel_36332/1634857678.py:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_temp[col] = row[col]

(30264, 501)

In [ ]:
df_isw_hourly['datetime'].min()

Timestamp('2022-02-24 00:00:00')

In [ ]:
df_isw_hourly['datetime'].max()

Timestamp('2026-03-16 23:00:00')

In [ ]:
df_isw_hourly[['datetime']].dtypes

datetime    datetime64[ns]
dtype: object

In [ ]:
df_isw_hourly.head()

,datetime,isw_tfidf_0,isw_tfidf_1,isw_tfidf_2,isw_tfidf_3,isw_tfidf_4,isw_tfidf_5,isw_tfidf_6,isw_tfidf_7,isw_tfidf_8,...,isw_tfidf_490,isw_tfidf_491,isw_tfidf_492,isw_tfidf_493,isw_tfidf_494,isw_tfidf_495,isw_tfidf_496,isw_tfidf_497,isw_tfidf_498,isw_tfidf_499
0,2022-02-24 00:00:00,0.012148,0.0,0.028729,0.026436,0.09456,0.0,0.027315,0.109427,0.010728,...,0.0,0.079702,0.0,0.036791,0.028086,0.0,0.013771,0.027594,0.0,0.039905
1,2022-02-24 01:00:00,0.012148,0.0,0.028729,0.026436,0.09456,0.0,0.027315,0.109427,0.010728,...,0.0,0.079702,0.0,0.036791,0.028086,0.0,0.013771,0.027594,0.0,0.039905
2,2022-02-24 02:00:00,0.012148,0.0,0.028729,0.026436,0.09456,0.0,0.027315,0.109427,0.010728,...,0.0,0.079702,0.0,0.036791,0.028086,0.0,0.013771,0.027594,0.0,0.039905
3,2022-02-24 03:00:00,0.012148,0.0,0.028729,0.026436,0.09456,0.0,0.027315,0.109427,0.010728,...,0.0,0.079702,0.0,0.036791,0.028086,0.0,0.013771,0.027594,0.0,0.039905
4,2022-02-24 04:00:00,0.012148,0.0,0.028729,0.026436,0.09456,0.0,0.027315,0.109427,0.010728,...,0.0,0.079702,0.0,0.036791,0.028086,0.0,0.013771,0.027594,0.0,0.039905

In [ ]:
df_isw_hourly.to_csv(path + 'isw_hourly.csv', index=False)

In [ ]:
df_telegram_merge = pd.read_csv(path + 'telegram_merge.csv')

In [ ]:
df_telegram_merge['datetime'].min()

Timestamp('2022-02-24 21:00:00')

In [ ]:
df_telegram_merge['datetime'].max()

Timestamp('2026-03-16 23:00:00')

In [ ]:
df_telegram_merge[['datetime']].dtypes

datetime    datetime64[ns]
dtype: object

In [ ]:
df_telegram_merge.head()

             datetime                                         tokens_str
0 2022-02-24 21:00:00  важливо терміново соцмережа деякий зе поширюва...
1 2022-02-24 22:00:00  повітрянин сила завдати ворог суттєвий втрата ...
2 2022-02-25 07:00:00  вибухи аеродромий міллєрово ростовській област...
3 2022-02-25 09:00:00  терміново кіберполіція створити спеціальний бо...
4 2022-02-25 10:00:00  бути україна stoprussia бути україна stoprussi...

In [ ]:
df_telegram_merge.to_csv(path + 'telegram_merge.csv', index=False)

In [ ]:
df_telegram_merge['datetime'] = df_telegram_merge['datetime'] + pd.Timedelta(hours=24)

In [ ]:
df_telegram_merge.to_csv(path + 'telegram_hourly.csv', index=False)

**MERGE WEATHER AND EVENTS**

In [ ]:
df_weather = pd.read_csv(path + 'weather_clean.csv', parse_dates=['datetime'])
df_alarms_hourly = pd.read_csv(path + 'alarms_hourly.csv', parse_dates=['datetime'])

In [ ]:
df_weather.shape

(808940, 26)

In [ ]:
df_alarms_hourly.shape

(178392, 5)

In [ ]:
df_weather[['datetime', 'region_id']].dtypes

datetime     datetime64[ns]
region_id             int64
dtype: object

In [ ]:
df_alarms_hourly[['datetime', 'region_id']].dtypes

datetime     datetime64[ns]
region_id             int64
dtype: object

In [ ]:
# LEFT JOIN(df_weather is our main matrix, df_alarms_hourly contains only the hours when an alarm was)
df_merged = df_weather.merge(
    df_alarms_hourly[['datetime', 'region_id', 'alarm']],
    on=['datetime', 'region_id'],
    how='left'
)

# Where there was no alarm, NaN appears, so we replace with 0
df_merged['alarm'] = df_merged['alarm'].fillna(0).astype(int)

In [ ]:
df_merged.shape

(808940, 27)

In [ ]:
(df_merged['alarm']==0).sum()

np.int64(638577)

In [ ]:
(df_merged['alarm']==1).sum()

np.int64(170363)

In [ ]:
df_merged.isnull().sum().sum()

np.int64(0)

In [ ]:
# For calculating the number of alarms in all regions for the current hour
df_merged['regions_in_alarm_now'] = df_merged.groupby('datetime')['alarm'].transform('sum')

In [ ]:
df_merged.head()

,city_latitude,city_longitude,city_address,hour_temp,hour_feelslike,hour_humidity,hour_dew,hour_precip,hour_precipprob,hour_snow,...,hour_uvindex,datetime,region_id,region,hour,month,season,is_weekend,alarm,regions_in_alarm_now
0,50.7469,25.3263,"Lutsk,Ukraine",2.4,-1.6,89.18,0.8,0.0,0.0,0.1,...,0.0,2022-02-24 00:00:00,3,Волинська,0,2,winter,0,0,0
1,50.7469,25.3263,"Lutsk,Ukraine",2.4,-1.5,87.90,0.6,0.0,0.0,0.0,...,0.0,2022-02-24 01:00:00,3,Волинська,1,2,winter,0,0,0
2,50.7469,25.3263,"Lutsk,Ukraine",2.9,-0.8,88.58,1.2,0.0,0.0,0.0,...,0.0,2022-02-24 02:00:00,3,Волинська,2,2,winter,0,0,0
3,50.7469,25.3263,"Lutsk,Ukraine",2.3,-1.3,86.63,0.3,0.0,0.0,0.0,...,0.0,2022-02-24 03:00:00,3,Волинська,3,2,winter,0,0,0
4,50.7469,25.3263,"Lutsk,Ukraine",1.9,-1.8,87.85,0.1,0.0,0.0,0.0,...,0.0,2022-02-24 04:00:00,3,Волинська,4,2,winter,0,0,0

In [ ]:
# For sorting the dataframe by region and time to prevent mixing data from different regions in the rolling window
df_merged = df_merged.sort_values(by=['region_id', 'datetime']).reset_index(drop=True)

# For calculating the rolling sum of alarms over the last 24 hours (shifting by 1 hour to exclude the current one)
df_merged['alarms_last_24h'] = df_merged.groupby('region_id')['alarm'].transform(
    lambda x: x.rolling(window=24, min_periods=1).sum().shift(1)
).fillna(0)

In [ ]:
df_merged.head()

,city_latitude,city_longitude,city_address,hour_temp,hour_feelslike,hour_humidity,hour_dew,hour_precip,hour_precipprob,hour_snow,...,datetime,region_id,region,hour,month,season,is_weekend,alarm,regions_in_alarm_now,alarms_last_24h
0,49.2336,28.4486,"Vinnytsia,Ukraine",2.1,-0.5,91.76,0.9,0.0,0.0,0.0,...,2022-02-24 00:00:00,2,Вінницька,0,2,winter,0,0,0,0.0
1,49.2336,28.4486,"Vinnytsia,Ukraine",2.1,-0.4,89.80,0.6,0.0,0.0,0.0,...,2022-02-24 01:00:00,2,Вінницька,1,2,winter,0,0,0,0.0
2,49.2336,28.4486,"Vinnytsia,Ukraine",2.0,-0.3,90.44,0.6,0.0,0.0,0.0,...,2022-02-24 02:00:00,2,Вінницька,2,2,winter,0,0,0,0.0
3,49.2336,28.4486,"Vinnytsia,Ukraine",1.9,-0.3,91.75,0.7,0.0,0.0,0.0,...,2022-02-24 03:00:00,2,Вінницька,3,2,winter,0,0,0,0.0
4,49.2336,28.4486,"Vinnytsia,Ukraine",1.8,-0.2,92.40,0.7,0.0,0.0,0.0,...,2022-02-24 04:00:00,2,Вінницька,4,2,winter,0,0,0,0.0

In [ ]:
# For extracting a time-based feature(1 if it's night from 22:00 - 06:00), 0 otherwise)
df_merged['is_night'] = df_merged['datetime'].dt.hour.apply(lambda x: 1 if (x >= 23 or x <= 6) else 0)

In [ ]:
df_merged.head()

,city_latitude,city_longitude,city_address,hour_temp,hour_feelslike,hour_humidity,hour_dew,hour_precip,hour_precipprob,hour_snow,...,region_id,region,hour,month,season,is_weekend,alarm,regions_in_alarm_now,alarms_last_24h,is_night
0,49.2336,28.4486,"Vinnytsia,Ukraine",2.1,-0.5,91.76,0.9,0.0,0.0,0.0,...,2,Вінницька,0,2,winter,0,0,0,0.0,1
1,49.2336,28.4486,"Vinnytsia,Ukraine",2.1,-0.4,89.80,0.6,0.0,0.0,0.0,...,2,Вінницька,1,2,winter,0,0,0,0.0,1
2,49.2336,28.4486,"Vinnytsia,Ukraine",2.0,-0.3,90.44,0.6,0.0,0.0,0.0,...,2,Вінницька,2,2,winter,0,0,0,0.0,1
3,49.2336,28.4486,"Vinnytsia,Ukraine",1.9,-0.3,91.75,0.7,0.0,0.0,0.0,...,2,Вінницька,3,2,winter,0,0,0,0.0,1
4,49.2336,28.4486,"Vinnytsia,Ukraine",1.8,-0.2,92.40,0.7,0.0,0.0,0.0,...,2,Вінницька,4,2,winter,0,0,0,0.0,1

In [ ]:
# For creating a lag feature(whether there was an alarm in this region exactly 24 hours ago)
df_merged['alarm_24h_ago'] = df_merged.groupby('region_id')['alarm'].shift(24).fillna(0)

In [ ]:
df_merged['alarm_24h_ago'].value_counts()

alarm_24h_ago
0.0    638790
1.0    170150
Name: count, dtype: int64

In [ ]:
df_merged.shape

(808940, 31)

In [ ]:
df_merged.to_csv(path + 'merged_weather_alarms.csv', index=False)